# Known Fontshare Fonts List
# This list contains fonts that are known to be available on Fontshare
# Last updated: June 2025

FONTSHARE_FONTS = [
    # Popular and widely used fonts
    "satoshi",
    "cabinet-grotesk", 
    "clash-display",
    "general-sans",
    "switzer",
    "clash-grotesk",
    "supreme",
    "author",
    "zodiak",
    "eiko",
    "fraktion",
    "sohne",
    "chillax",
    "sentient",
    "tanker",
    "synonym",
    "boska",
    "melodrama",
    "alpino",
    "ranade",
    "sohne-mono",
    "khand",
    "gambetta",
    "erode",
    "product-sans",
    "dma-sans",
    "satoshi-variable",
    "cabinet-grotesk-variable",
    "clash-display-variable",
    "general-sans-variable",
    "switzer-variable",
    
    # Additional fonts that may be available
    "clash-text",
    "sentient-variable",
    "author-variable",
    "supreme-variable",
    "zodiak-variable",
    "tanker-variable",
    "synonym-variable",
    "boska-variable",
    "alpino-variable",
    "ranade-variable",
    "khand-variable",
    "gambetta-variable",
    "erode-variable",
    "fraktion-variable",
    "eiko-variable",
    "sohne-variable",
    "chillax-variable",
    "melodrama-variable"
]

# Additional fonts to test (may or may not be available)
POTENTIAL_FONTS = [
    "inter",
    "poppins", 
    "nunito",
    "lexend",
    "space-grotesk",
    "dm-sans",
    "plus-jakarta-sans",
    "work-sans",
    "ibm-plex-sans",
    "red-hat-display",
    "fira-sans",
    "source-sans-pro",
    "open-sans",
    "roboto",
    "lato",
    "montserrat",
    "oswald",
    "raleway",
    "ubuntu",
    "playfair-display",
    "merriweather",
    "lora",
    "crimson-text",
    "pt-sans",
    "noto-sans"
]
